buckets = [
    'extras',
    'main',
]

[[entries]]
name = '7zip'
version = '19.00'

[[entries]]
name = 'alacritty'
version = '0.7.2'

[[entries]]
name = 'aria2'
version = '1.35.0-1'

[[entries]]
name = 'cudatext'
version = '1.132.0.5'
