buckets = [
    'extras',
    'main',
]

[[entries]]
name = '7zip'
version = '19.00'

[[entries]]
name = 'alacritty'
version = '0.7.2'

[[entries]]
name = 'aria2'
version = '1.35.0-1'

[[entries]]
name = 'cudatext'
version = '1.132.0.5'

[[entries]]
name = 'docker'
version = '19.03.1'

[[entries]]
name = 'fd'
version = '8.2.1'

[[entries]]
name = 'ffmpeg'
version = '4.4-4'

[[entries]]
name = 'firefox'
version = '87.0'

[[entries]]
name = 'freebasic'
version = '1.07.3'

[[entries]]
name = 'freecad'
version = '0.18.4'

[[entries]]
name = 'fzf'
version = '0.27.0'

[[entries]]
name = 'genact'
version = '0.11.0'

[[entries]]
name = 'gh'
version = '1.9.1'

[[entries]]
name = 'gimp'
version = '2.10.20-1'

[[entries]]
name = 'git'
version = '2.31.1.windows.1'

[[entries]]
name = 'git-chglog'
version = '0.14.2'

[[entries]]
name = 'gitui'
version = '0.14.0'

[[entries]]
name = 'iconv'
version = '1.14-3'

[[entries]]
name = 'innounp'
version = '0.50'

[[entries]]
name = 'irfanview'
version = '4.57'

[[entries]]
name = 'kate'
version = '20.12.3-1245'

[[entries]]
name = 'krita'
version = '4.4.3'

[[entries]]
name = 'latex'
version = '21.2'

[[entries]]
name = 'librecad'
version = '2.1.3'

[[entries]]
name = 'libreoffice-stable'
version = '7.1.1'

[[entries]]
name = 'lsd'
version = '0.20.1'

[[entries]]
name = 'lua'
version = '5.4.3'

[[entries]]
name = 'markdown-monster'
version = '1.26.10'

[[entries]]
name = 'notepad2'
version = '4.2.25'

[[entries]]
name = 'notepad3'
version = '5.20.722.1'

[[entries]]
name = 'notepadplusplus'
version = '7.9.5'

[[entries]]
name = 'premake'
version = '5.0.0-alpha16'

[[entries]]
name = 'sfk'
version = '1.9.8.0'

[[entries]]
name = 'shadered'
version = '1.5.1'

[[entries]]
name = 'standardnotes'
version = '3.6.7'

[[entries]]
name = 'starship'
version = '0.51.0'

[[entries]]
name = 'vcredist2010'
version = '10.0.40219.473'

[[entries]]
name = 'vcredist2015'
version = '14.0.24215'

[[entries]]
name = 'vcredist2017'
version = '14.16.27027.1'

[[entries]]
name = 'vscodium'
version = '1.55.2'

[[entries]]
name = 'whatsapp'
version = '2.2112.10'

[[entries]]
name = 'youtube-dl'
version = '2021.04.17'
